### ISSUE TITLE
patching dosent work

### ISSUE THREAD

**Issue by Assertores** [Assertores/Einkaufsliste#22]
# description

while downloading the update the zip can not be extracted which ends in the recursive_directory_iterator to fail

# reproduction steps

1. download prerelease v0.0.1
2. extract it somewhere
3. open version.txt
4. change content to v0.0.0
5. open cmd
6. run `Einkaufsliste.exe` with commandline `--prerelease`

programm crashes

## expected behaviour

programm should update itself.

# files

# remarks

a `patch.zip` is downloaded but is somehow corupt

**Comment by Green-Sky** [comment]
![image](https://user-images.githubusercontent.com/2938071/147003353-f1be1f43-1fb7-4d7d-8845-c3eecc42d6ca.png)

**Comment by Assertores** [comment]
`0A` is line feed. `0D` is cariar return. windows apparently changed `lf` to be `crlf`
